// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {request} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Send(arg1:request.Request):Promise<request.Response>;
