// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { curler } from "../models"

export function Greet(arg1: string): Promise<string>

export function Send(arg1: curler.RequestOptions): Promise<curler.Response>
